[project]
name = "candidate-tracker-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Michael Faniyi", email = "michaelfa@ha-shem.com" }
]
requires-python = ">=3.14"
dependencies = [
    "email-validator>=2.3.0",
    "fastapi[standard]>=0.141.1",
    "httpx>=0.28.1",
    "pytest>=9.1.1",
]

[project.scripts]
candidate-tracker-app = "candidate_tracker_app:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
